#!/usr/bin/env python3
"""Link a code overlay against a resident program.

An overlay is assembled like any other module and may import engine
routines.  Those live at fixed addresses in the resident program, so this
tool reads the program's VICE label file (ld65 -Ln), takes every symbol
the engine declares .global in include/b64.inc, turns each into a linker
define, and links the overlay for its window with overlay.cfg.

usage: b64overlay.py <program.lbl> <overlay.cfg> <overlay.o> <out.bin> [--inc out.inc prefix,prefix]

--inc writes the overlay's own symbols whose names start with one of the
prefixes as `name = $address` lines, for a game to assemble against (a
pinned module's body tables, docs/PHYSICS.md).
"""
import re, subprocess, sys


def engine_globals():
    text = open("include/b64.inc").read()
    return set(re.findall(r"^\.global\s+([A-Za-z_][A-Za-z0-9_]*)", text, re.M))


def labels(lbl_path):
    out = {}
    for line in open(lbl_path):
        m = re.match(r"al ([0-9A-Fa-f]{6}) \.([A-Za-z_][A-Za-z0-9_]*)$", line.strip())
        if m:
            out[m.group(2)] = m.group(1)
    return out


def main():
    lbl_path, cfg, obj, out = sys.argv[1:5]
    wanted = engine_globals()
    found = labels(lbl_path)
    defs = []
    for name in sorted(wanted):
        if name in found:
            defs += ["-D", f"{name}=${found[name]}"]
    inc = None
    lbl_out = out + ".lbl"                   # always: the checks and the probe read a module's labels
    defs += ["-Ln", lbl_out]
    if "--inc" in sys.argv:
        k = sys.argv.index("--inc")
        inc, prefixes = sys.argv[k + 1], tuple(sys.argv[k + 2].split(","))
    cmd = ["ld65", "-C", cfg, "-o", out] + defs + [obj]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(r.stderr)
        raise SystemExit(f"overlay link failed for {obj}")
    size = len(open(out, "rb").read())
    print(f"  {out}: {size} bytes")
    if inc:
        own = labels(lbl_out)
        with open(inc, "w") as f:
            f.write(f"; generated by tools/b64overlay.py from {obj}\n")
            for name in sorted(own):
                if name.startswith(prefixes) and name not in wanted:
                    f.write(f"{name:<16} = ${own[name][2:]}\n")


if __name__ == "__main__":
    main()
