#!/usr/bin/env python3
"""Tables for the physics module (modules/physics): the sine of each of the
256 headings in 1.7 fixed point (127 = 1), and the mass shares for
collisions, round(127 * mj / (mi + mj)) for masses 0-15.  Written as an
include the module assembles.

usage: b64phystab.py <out.inc>
"""
import math
import sys

out = sys.argv[1]
lines = ["; generated by tools/b64phystab.py", "phys_sine:"]
vals = [round(127 * math.sin(2 * math.pi * k / 256)) for k in range(256)]
for i in range(0, 256, 16):
    lines.append("        .byte " + ", ".join(str(v & 255) for v in vals[i:i + 16]))
lines.append("phys_share:                     ; [mi * 16 + mj]: the share of a collision's change mass i takes")
for i in range(16):
    row = [0 if i + j == 0 or i == 0 or j == 0 else round(127 * j / (i + j)) for j in range(16)]
    lines.append("        .byte " + ", ".join(map(str, row)))
open(out, "w").write("\n".join(lines) + "\n")
