#!/usr/bin/env python3
"""backlot-64 REU image packer.

Lays out an REU image from a manifest and emits slots.inc with the REU
address of every slot so nothing in assembly hard-codes an offset.

Manifest is a text file, one slot per line:

    size    8192              ; image size in KiB (VICE -reusize)
    slot    WORLD    $000000  build/world.map
    slot    REGIONS  $400000  build/world.reg
    slot    TILESET0 $401000  build/vice_day.bin
    slot    SPRITES0 $431000  build/sprites0.spr
    slot    SCRATCH  $7F0000  -

A '-' file reserves the slot without contents.

usage: b64pack.py <manifest> <out.reu> <out.inc|->
       b64pack.py --inc <manifest> <out.inc>   (addresses only, no files needed)
"""
import sys


def parse_addr(s):
    return int(s[1:], 16) if s.startswith("$") else int(s, 0)


def main():
    inc_only = sys.argv[1] == "--inc"
    if inc_only:
        manifest, out_reu, out_inc = sys.argv[2], None, sys.argv[3]
    else:
        manifest, out_reu, out_inc = sys.argv[1], sys.argv[2], sys.argv[3]
    size_kib = 8192
    slots = []
    with open(manifest) as f:
        for line in f:
            line = line.split(";")[0].strip()
            if not line:
                continue
            parts = line.split()
            if parts[0] == "size":
                size_kib = int(parts[1])
            elif parts[0] == "slot":
                slots.append((parts[1], parse_addr(parts[2]), parts[3]))
    image = bytearray(size_kib * 1024)
    placed = []
    for name, addr, path in slots:
        if inc_only:
            placed.append((name, addr, 0))
            continue
        if path != "-":
            with open(path, "rb") as f:
                data = f.read()
            if addr + len(data) > len(image):
                raise SystemExit(f"slot {name} at ${addr:06X} + {len(data)} bytes exceeds the {size_kib} KiB image")
            image[addr:addr + len(data)] = data
            placed.append((name, addr, len(data)))
        else:
            placed.append((name, addr, 0))
    for i in range(len(placed) - 1):
        n, a, ln = placed[i]
        n2, a2, _ = placed[i + 1]
        if a + ln > a2:
            raise SystemExit(f"slot {n} overlaps {n2}")
    if out_reu:
        with open(out_reu, "wb") as f:
            f.write(image)
    if out_inc != "-":
        with open(out_inc, "w") as f:
            f.write("; generated by b64pack.py -- REU slot addresses\n")
            f.write(f"REU_SIZE_KIB = {size_kib}\n")
            for name, addr, ln in placed:
                f.write(f"SLOT_{name:<12} = ${addr:06X}\n")
    for name, addr, ln in placed:
        print(f"  {name:<12} ${addr:06X}  {ln:>8} bytes")


if __name__ == "__main__":
    main()
