; backlot-64 scroller: 8-way hardware scroll over the REU world.
;
; Two screen buffers, and in REU scratch a copy of the screen being shown.
; When the camera crosses a cell boundary the scratch copy is fetched into
; the back buffer with a byte offset (dx + 40*dy), the newly exposed column
; and/or row are filled from the metatile library, and the finished back
; buffer is stashed to scratch.  In the vertical border that same copy is
; fetched into colour RAM and the buffers flip.  See docs/PLAN.md 3.1.
;
; Colour is packed in the screen code: a scene character's colour is the
; low four bits of its code (tools/b64tileset.py assigns the codes), and
; colour RAM keeps only the low four bits of what is written to it, so
; colour RAM is the screen itself.  The fills move one byte per cell and
; never touch colour.
; After Lasse Öörni (Cadaver), c64gameframework (macros.s, drawfullblock).
; Changed: colour RAM is written by one DMA from the REU copy of the
; finished screen rather than by the fill loops, so the source's
; per-block colour flags are not needed.  Measured in docs/JOURNAL.md.

.include "b64.inc"
.include "slots.inc"

.export scr_vblank
.import hud_flush

SCREEN_BYTES    = B64_PLAY_ROWS * 40      ; 920: rows 0-22 shift, the HUD rows stay

.segment "LOWRAM"
mt_buf:         .res 16         ; metatile ids of the column or row being filled
colbuf:         .res 28         ; a column's cells from its 7 metatiles, top to bottom

; id -> MTCHARS + id*16, as tables generated by scr_tables; the library by
; column is the same offset 4 KB higher
MT16_LO         = B64_MT16
MT16_HI         = B64_MT16 + $100
.assert (B64_MTCHARS & $0FFF) = 0, error, "scr_tables assumes MTCHARS on a 4 KB boundary"
.assert B64_MTCOLUMNS = B64_MTCHARS + $1000, error, "fill_col finds the library by column with ORA #$10"
.assert (SLOT_SCRATCH & $FFFF) = 0, error, "shift_buffer adds the offset to SLOT_SCRATCH's low bytes"

.segment "RODATA"
row_lo:
.repeat 25, r
        .byte <(r*40)
.endrepeat
row_hi:
.repeat 25, r
        .byte >(r*40)
.endrepeat

.segment "CODE"

; ---------------------------------------------------------------------------
; b64_move_camera: A = dx, X = dy, signed
b64_move_camera:
        sta b64_tmp
        stx b64_tmp+1
        ; cam_x += dx
        lda b64_tmp
        bpl :+
        clc
        adc b64_cam_x
        sta b64_cam_x
        lda b64_cam_x+1
        adc #$FF
        sta b64_cam_x+1
        jmp @y
:       clc
        adc b64_cam_x
        sta b64_cam_x
        lda b64_cam_x+1
        adc #0
        sta b64_cam_x+1
@y:     lda b64_tmp+1
        bpl :+
        clc
        adc b64_cam_y
        sta b64_cam_y
        lda b64_cam_y+1
        adc #$FF
        sta b64_cam_y+1
        rts
:       clc
        adc b64_cam_y
        sta b64_cam_y
        lda b64_cam_y+1
        adc #0
        sta b64_cam_y+1
        rts

; ---------------------------------------------------------------------------
; camera pixels -> camera cells (scr_cx/scr_cy) and fine scroll (scr_xs/scr_ys)
calc_cam:
        lda b64_cam_x+1
        sta scr_cx+1
        lda b64_cam_x
        sta scr_cx
        lsr scr_cx+1
        ror scr_cx
        lsr scr_cx+1
        ror scr_cx
        lsr scr_cx+1
        ror scr_cx
        lda b64_cam_y+1
        sta scr_cy+1
        lda b64_cam_y
        sta scr_cy
        lsr scr_cy+1
        ror scr_cy
        lsr scr_cy+1
        ror scr_cy
        lsr scr_cy+1
        ror scr_cy
        lda b64_cam_x
        and #7
        eor #7
        sta scr_xs
        lda b64_cam_y
        and #7
        eor #7
        sta scr_ys
        rts

; ---------------------------------------------------------------------------
; b64_scroll_prepare: called by the engine once per frame after the callback.
b64_scroll_prepare:
        jsr calc_cam
        ; dx = cx - ocx  (expected -1, 0, 1), dy likewise
        lda scr_cx
        sec
        sbc scr_ocx
        sta b64_tmp             ; dx (low byte is enough)
        lda scr_cy
        sec
        sbc scr_ocy
        sta b64_tmp+1           ; dy
        ora b64_tmp
        bne @shift
        ; no cell crossing: only the fine scroll registers
        lda #1
        sta scr_pending
        rts

@shift:
        ; back buffer high byte
        lda scr_front
        beq :+
        lda #>B64_SCREEN_A
        bne :++
:       lda #>B64_SCREEN_B
:       sta scr_back_hi

        ; off = dx + 40*dy as signed 16-bit
        lda #0
        sta scr_off_hi
        lda b64_tmp+1
        beq @nody
        bpl @dyp
        lda #<(-40)
        sta scr_off_lo
        lda #>(-40)
        sta scr_off_hi
        jmp @adddx
@dyp:   lda #40
        sta scr_off_lo
        jmp @adddx
@nody:  sta scr_off_lo
@adddx:
        lda b64_tmp
        beq @offdone
        bpl @dxp
        lda scr_off_lo
        sec
        sbc #1
        sta scr_off_lo
        bcs @offdone
        dec scr_off_hi
        jmp @offdone
@dxp:   inc scr_off_lo
        bne @offdone
        inc scr_off_hi
@offdone:

        ; screen shift: the shown screen, from scratch, into the back buffer
        jsr shift_buffer

        ; which edges to fill
        lda #$FF
        sta scr_newcol
        sta scr_newrow
        lda b64_tmp
        beq @nocol
        bpl :+
        lda #0
        sta scr_newcol
        beq @nocol
:       lda #39
        sta scr_newcol
@nocol:
        lda b64_tmp+1
        beq @norow
        bpl :+
        lda #0
        sta scr_newrow
        beq @norow
:       lda #(B64_PLAY_ROWS - 1)
        sta scr_newrow
@norow:
        lda scr_newcol
        cmp #$FF
        beq :+
        jsr fill_col
:       lda scr_newrow
        cmp #$FF
        beq :+
        jsr fill_row
:       ; the finished back buffer becomes the scratch copy: the next shift
        ; reads it, and the vertical border fetches it into colour RAM
        lda #0
        sta b64_ptr
        lda scr_back_hi
        sta b64_ptr+1
        B64_SET16 b64_len, SCREEN_BYTES
        B64_SET24 b64_reu, SLOT_SCRATCH
        jsr b64_stash
        lda scr_cx
        sta scr_ocx
        lda scr_cx+1
        sta scr_ocx+1
        lda scr_cy
        sta scr_ocy
        lda scr_cy+1
        sta scr_ocy+1
        lda #3
        sta scr_pending
        rts

; ---------------------------------------------------------------------------
; shift_buffer: back[i] = shown[i + off], one fetch from the REU copy of the
; shown screen, with the signed offset in scr_off.
shift_buffer:
        lda scr_off_hi
        bmi @neg
        ; off >= 0: from scratch + off into back, 920 - off bytes
        lda scr_off_lo
        sta b64_reu
        lda scr_off_hi
        sta b64_reu+1
        lda #^SLOT_SCRATCH
        sta b64_reu+2
        lda #0
        sta b64_ptr
        lda scr_back_hi
        sta b64_ptr+1
        lda #<SCREEN_BYTES
        sec
        sbc scr_off_lo
        sta b64_len
        lda #>SCREEN_BYTES
        sbc scr_off_hi
        sta b64_len+1
        jmp b64_fetch
@neg:   ; off < 0: from scratch into back - off, 920 + off bytes
        B64_SET24 b64_reu, SLOT_SCRATCH
        lda #0
        sec
        sbc scr_off_lo
        sta b64_ptr
        lda scr_back_hi
        sbc scr_off_hi
        sta b64_ptr+1
        lda #<SCREEN_BYTES
        clc
        adc scr_off_lo
        sta b64_len
        lda #>SCREEN_BYTES
        adc scr_off_hi
        sta b64_len+1
        jmp b64_fetch

; ---------------------------------------------------------------------------
; reu_map_addr: b64_reu = (scr_my << 11) | scr_mx   (world is 2048 wide)
reu_map_addr:
        lda scr_mx
        sta b64_reu
        lda scr_my
        and #$1F
        asl
        asl
        asl
        ora scr_mx+1
        sta b64_reu+1
        lda scr_my
        lsr
        lsr
        lsr
        lsr
        lsr
        sta b64_tmp+4
        lda scr_my+1
        asl
        asl
        asl
        ora b64_tmp+4
        sta b64_reu+2
        rts

; scr_tables: MT16_LO/HI[id] = MTCHARS + id*16
scr_tables:
        ldx #0
:       txa
        asl
        asl
        asl
        asl
        sta MT16_LO,x
        txa
        lsr
        lsr
        lsr
        lsr
        ora #>B64_MTCHARS
        sta MT16_HI,x
        inx
        bne :-
        rts

; col_ids: the 7 metatile ids down a world column, from b64_reu, 2048 apart
; in the REU, into mt_buf.  The first transfer sets every register; the rest
; rewrite only the REU address and the command, because a transfer leaves
; the C64 address advanced past the byte and the length at 1.
col_ids:
        php
        sei
        lda #<mt_buf
        sta REU_C64_LO
        lda #>mt_buf
        sta REU_C64_HI
        lda #1
        sta REU_LEN_LO
        lda #0
        sta REU_LEN_HI
        sta REU_CTRL
        ldx #7
@f:     lda b64_reu
        sta REU_ADDR_LO
        lda b64_reu+1
        sta REU_ADDR_HI
        lda b64_reu+2
        sta REU_BANK
        lda #REU_CMD_FETCH
        sta REU_CMD
        lda b64_reu+1
        clc
        adc #8
        sta b64_reu+1
        bcc :+
        inc b64_reu+2
:       dex
        bne @f
        plp
        rts

; ---------------------------------------------------------------------------
; fill_col: A = screen column.  Screen codes into the back buffer.
; The column crosses at most 7 metatiles.  Their column slices are gathered
; from the library by column, four cells in a run, then written down the
; screen with one unrolled store per row.
fill_col:
        sta scr_i
        clc
        lda scr_cx
        adc scr_i
        sta scr_wx
        lda scr_cx+1
        adc #0
        sta scr_wx+1
        ; mx = wx >> 2, my = cy >> 2
        lda scr_wx+1
        sta scr_mx+1
        lda scr_wx
        sta scr_mx
        lsr scr_mx+1
        ror scr_mx
        lsr scr_mx+1
        ror scr_mx
        lda scr_cy+1
        sta scr_my+1
        lda scr_cy
        sta scr_my
        lsr scr_my+1
        ror scr_my
        lsr scr_my+1
        ror scr_my
        jsr reu_map_addr
        jsr col_ids
        lda scr_wx
        and #3
        asl
        asl
        sta scr_sub             ; the column's first cell in every metatile's by-column slice
        lda #0
        sta b64_tmp+4           ; metatile index
        tax                     ; colbuf index
@mt:    ldy b64_tmp+4
        lda mt_buf,y
        tay
        lda MT16_LO,y
        ora scr_sub
        sta scr_q
        lda MT16_HI,y
        ora #>(B64_MTCOLUMNS - B64_MTCHARS)
        sta scr_q+1
        inc b64_tmp+4
        ldy #0
        lda (scr_q),y
        sta colbuf,x
        iny
        lda (scr_q),y
        sta colbuf+1,x
        iny
        lda (scr_q),y
        sta colbuf+2,x
        iny
        lda (scr_q),y
        sta colbuf+3,x
        txa
        clc
        adc #4
        tax
        cpx #28
        bcc @mt
        ; row r is colbuf[(cy & 3) + r]
        lda scr_cy
        and #3
        tay
        ldx scr_i
        lda scr_back_hi
        cmp #>B64_SCREEN_B
        bne :+
        jmp @b                  ; the unrolled block is beyond a branch's reach
:
.repeat B64_PLAY_ROWS, r
        lda colbuf+r,y
        sta B64_SCREEN_A + r*40,x
.endrepeat
        rts
@b:
.repeat B64_PLAY_ROWS, r
        lda colbuf+r,y
        sta B64_SCREEN_B + r*40,x
.endrepeat
        rts

; ---------------------------------------------------------------------------
; fill_row: A = screen row.  Screen codes into the back buffer.
fill_row:
        sta scr_i
        clc
        lda scr_cy
        adc scr_i
        sta scr_wy
        lda scr_cy+1
        adc #0
        sta scr_wy+1
        ; mx = cx >> 2, my = wy >> 2
        lda scr_cx+1
        sta scr_mx+1
        lda scr_cx
        sta scr_mx
        lsr scr_mx+1
        ror scr_mx
        lsr scr_mx+1
        ror scr_mx
        lda scr_wy+1
        sta scr_my+1
        lda scr_wy
        sta scr_my
        lsr scr_my+1
        ror scr_my
        lsr scr_my+1
        ror scr_my
        jsr reu_map_addr
        B64_SET16 b64_ptr, mt_buf
        B64_SET16 b64_len, 11   ; 40 cells from any starting column span at most 11 metatiles
        jsr b64_fetch
        ; the row's address in the back buffer goes into the stores below
        ldx scr_i
        lda row_lo,x
        sta @s0+1
        sta @s1+1
        sta @s2+1
        sta @s3+1
        sta @st+1
        lda row_hi,x
        clc
        adc scr_back_hi
        sta @s0+2
        sta @s1+2
        sta @s2+2
        sta @s3+2
        sta @st+2
        lda scr_wy
        and #3
        asl
        asl
        sta scr_sub             ; the row within every metatile, * 4
        lda scr_cx
        and #3
        sta b64_tmp+5           ; the first metatile starts at column (cx & 3)
        lda #0
        sta b64_tmp+4           ; metatile index
        tax                     ; screen column
@mt:    ldy b64_tmp+4
        lda mt_buf,y
        tay
        lda MT16_LO,y
        ora scr_sub
        sta scr_q
        lda MT16_HI,y
        sta scr_q+1
        inc b64_tmp+4
        ldy b64_tmp+5
        bne @c                  ; the first metatile, part-way in: a cell at a time
        cpx #37
        bcs @c                  ; fewer than four columns left: a cell at a time
        lda (scr_q),y           ; a whole metatile row, unrolled
@s0:    sta $FFFF,x
        inx
        iny
        lda (scr_q),y
@s1:    sta $FFFF,x
        inx
        iny
        lda (scr_q),y
@s2:    sta $FFFF,x
        inx
        iny
        lda (scr_q),y
@s3:    sta $FFFF,x
        inx
        cpx #40
        bcc @mt
        rts
@c:     lda (scr_q),y
@st:    sta $FFFF,x
        inx
        cpx #40
        beq @done
        iny
        cpy #4
        bne @c
        lda #0
        sta b64_tmp+5           ; every metatile after the first starts at its left edge
        beq @mt
@done:  rts

; ---------------------------------------------------------------------------
; b64_redraw: rebuild the front buffer, its REU copy and colour RAM from the
; camera.  Call after loading a tileset or moving the camera by more than a cell.
b64_redraw:
        jsr scr_tables
        jsr calc_cam
        lda scr_front
        beq :+
        lda #>B64_SCREEN_B
        bne :++
:       lda #>B64_SCREEN_A
:       sta scr_back_hi         ; fill into the front buffer directly
        lda #0
        sta b64_tmp+7
@row:   lda b64_tmp+7
        jsr fill_row
        inc b64_tmp+7
        lda b64_tmp+7
        cmp #B64_PLAY_ROWS
        bne @row
        ; the REU copy, then colour RAM from it
        lda #0
        sta b64_ptr
        lda scr_back_hi
        sta b64_ptr+1
        B64_SET16 b64_len, SCREEN_BYTES
        B64_SET24 b64_reu, SLOT_SCRATCH
        jsr b64_stash
        B64_SET16 b64_ptr, B64_COLOR_RAM
        B64_SET16 b64_len, SCREEN_BYTES
        B64_SET24 b64_reu, SLOT_SCRATCH
        jsr b64_fetch
        lda scr_cx
        sta scr_ocx
        lda scr_cx+1
        sta scr_ocx+1
        lda scr_cy
        sta scr_ocy
        lda scr_cy+1
        sta scr_ocy+1
        lda #$FF
        sta scr_newcol
        sta scr_newrow
        jsr apply_regs
        lda #0
        sta scr_pending
        rts

; ---------------------------------------------------------------------------
; scr_vblank: called from the engine IRQ at the bottom of the display.
scr_vblank:
        lda scr_pending
        beq @done
        and #2
        beq @regs
        ; colour RAM is the screen about to be shown: one fetch of its REU copy
        B64_SET16 b64_ptr, B64_COLOR_RAM
        B64_SET16 b64_len, SCREEN_BYTES
        B64_SET24 b64_reu, SLOT_SCRATCH
        jsr b64_fetch
        lda scr_front
        eor #1
        sta scr_front
@regs:  jsr apply_regs
        lda #0
        sta scr_pending
@done:  jsr hud_flush
        ; pinned sprite 0 pointer in both buffers
        lda b64_spr0_frame
        clc
        adc #B64_SPR_BASE
        sta B64_SPR_PTR_A
        sta B64_SPR_PTR_B
        rts

; video matrix and fine scroll registers from scr_front / scr_xs / scr_ys
apply_regs:
        lda scr_front
        beq :+
        lda #%00010010          ; screen B
        bne :++
:       lda #%00000010          ; screen A
:       sta VIC_VIDEO_ADR
        lda scr_xs
        ora #%00010000
        sta VIC_CTRL2
        lda scr_ys
        ora #%00010000
        sta VIC_CTRL1
        rts
